Repository mormaer/Mlem, pull requests merged in 2023-06, with the labels that each got.

#182 Improved VO for Post and Comments.
  Mlem/Views/Tabs/Posts/Components/Comment/Components/Comment Item.swift
  Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Components/Large Post.swift
  Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Components/Post Header.swift
  Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Components/Post Interaction Bar.swift
  Mlem/Views/Tabs/Posts/Components/Shared/Buttons/Vote Complex/Vote Complex.swift
Labels: accessibility

#183 Fix VO issues with community view
  Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Community View.swift
Labels: accessibility

#185 Fix for navigating to community from a post
  Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Components/Post Header.swift
Labels: accessibility

#197 Added new Community List page to the login flow
  Mlem.xcodeproj/project.pbxproj
  Mlem/API/Models/Community/APICommunity.swift
  Mlem/API/Requests/Community/ListCommunities.swift
  Mlem/Logic/Get Favorited Communities.swift
  Mlem/Models/Trackers/Favorite Community Tracker.swift
  Mlem/Views/Tabs/Posts/Components/Post/Components/Community List View/Community List View.swift
  Mlem/Views/Tabs/Posts/Components/Post/Components/Community List View/Components/CommunityListRowViews.swift
  Mlem/Views/Tabs/Posts/Components/Post/Components/Community List View/Components/CommunityListSidebarEntry.swift
  Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Community Search/Community Search View.swift
  Mlem/Views/Tabs/Posts/Components/Post/Components/Instance and Community List/Accounts Page.swift
Labels: on hold

#353 Fix community list accessibility
  Mlem/Views/Tabs/Posts/Components/Post/Components/Community List View/Components/CommunityListRowViews.swift
Labels: bug, accessibility

#356 Fixed some issues reading posts
  Mlem/Views/Shared/Loading View.swift
  Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Feed Post.swift
  Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Components/Post Interaction Bar.swift
  Mlem/Views/Tabs/Posts/Components/Post/Components/Community View/Post Item/Post Types/Large Post.swift
  Mlem/Views/Tabs/Posts/Components/Shared/Buttons/Save.swift
  Mlem/Views/Tabs/Posts/Components/Shared/Buttons/Share.swift
Labels: bug, accessibility
